language: cpp
compiler: gcc

install:
  # Put ChaiScript in folder next to this one
  - my_github=${PWD##*/}  
  - cd ..
  - git clone https://github.com/ChaiScript/ChaiScript.git
  - cd $my_github

script: 
  - qmake
  - make
  - ./travis_qmake_gcc_cpp98_chaiscript
